version: "3.3"
services:
  # comment for no-ssl
  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/../front/front-end/build:/srv
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - autoexam.env

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

  mysql:
    container_name: mysql-exam
    image: mysql/mysql-server:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - mysql-exam-db:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:6.2.6
    ports:
      - 6379:6379

  backend:
    container_name: backend
    image: golang
    depends_on:
      - mysql-exam
      - mongodb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./back-end:/backend
    working_dir: /backend
    command: ./run.sh

  worker:
    container_name: worker
    image: golang
    depends_on:
      - mysql-exam
      - mongodb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./back-end:/backend
    working_dir: /backend
    command: ./run_worker.sh
    
volumes:
  mongodb:
  mysql-exam-db:
  caddy_data:
  caddy_config: