definitions:
  authentication.Info:
    properties:
      client_id:
        type: string
      scope:
        type: string
    type: object
  models.UserToken:
    properties:
      id:
        type: integer
      token:
        type: string
    type: object
  response.Error:
    properties:
      message:
        type: string
      type:
        type: string
    type: object
  response.SwaggerResponse:
    properties:
      data: {}
      error:
        $ref: '#/definitions/response.Error'
      type:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /auth/info:
    get:
      consumes:
      - application/json
      description: get autolab authentication info
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/authentication.Info'
      summary: get auth info
      tags:
      - auth
  /test/login/:
    get:
      consumes:
      - application/json
      description: test
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/models.UserToken'
      summary: test
      tags:
      - test
  /test/user/:
    get:
      consumes:
      - application/json
      description: test
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
      security:
      - ApiKeyAuth: []
      summary: test
      tags:
      - test
  /test/users/:
    get:
      consumes:
      - application/json
      description: test
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
      security:
      - ApiKeyAuth: []
      summary: test
      tags:
      - test
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
