name: "backend-auth-test"
port: 9097
logsAddress: "./logs/"

# "info" for all http request, "alarm" for all non 200 http request
logger: "info" 

mysql:
 name: "user"
 host: "18.219.35.63"
 port: 3306
 password: "password"
 dbName: "xxxxx"
 
autolab:
  ip: "18.219.35.63"
  client_id: "tu0V2ggc8b5RDPEgwWIig0abCLY_MnpyaAOYMZCBF-Q"
  client_secret: "_xlQUFMH0Qs7dm8G3XW8852asnPykqsBneQ6KoRicS0"
  redirect_uri: "https://sie-examserver-frontend.herokuapp.com/oauth-callback"
  scope:  "user_info user_courses user_scores user_submit instructor_all admin_all"
