name: "123"
port: 8080
logsAddress: "./backend_logs/"

# "info" for all http request, "alarm" for all non 200 http request
logger: "info" 

mysql:
 name: "user"
 host: "3.141.18.114"
 port: 3306
 password: "password"
 dbName: "autolab_development"

autolab:
  protocol: http  # http or https
  ip: "3.141.18.114"
  client_id: "tu0V2ggc8b5RDPEgwWIig0abCLY_MnpyaAOYMZCBF-Q"
  client_secret: "_xlQUFMH0Qs7dm8G3XW8852asnPykqsBneQ6KoRicS0"
  redirect_uri: "https://sie-examserver-frontend.herokuapp.com/oauth-callback"
  scope:  "user_info user_courses user_scores user_submit instructor_all admin_all"

jwt:
  key: "CJzzsyJ7FRqWRQn8UkqOGn6tEishf0sgbwJt75H1O6ztnpEPVOAlwCkoKjWbbejoJnPLWBNW5TW7tHRWfh2nNoCdEpkkSTQADf0"